


export function Home() {
    return (
        <section className="home card">
            <h1>Welcome to Our Books Shop !</h1>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse quidem deserunt ut, placeat adipisci totam quo dignissimos vel deleniti, sapiente tenetur quia sint ducimus architecto quisquam, inventore veniam officiis nisi! Ea placeat minus, quidem, blanditiis modi recusandae illo ipsam deleniti voluptates fuga quis itaque, officiis sit hic autem! Nostrum neque accusamus, et doloribus fuga deserunt reprehenderit aspernatur voluptates iusto natus distinctio, saepe eveniet veritatis commodi fugit possimus odit rerum voluptatum. Molestiae similique a aspernatur provident iste. Provident hic fuga quo odit velit nostrum earum natus inventore voluptatum, odio laboriosam blanditiis quidem facere laudantium aspernatur aliquam omnis quaerat, suscipit consequuntur illo dicta impedit, ut dolores architecto! Quidem quod natus mollitia laborum distinctio ratione excepturi voluptatibus, rem facere aliquam expedita reiciendis enim architecto, beatae velit! Perferendis ducimus ipsam ab soluta nostrum fugit? A, itaque nobis? Ad nemo itaque recusandae exercitationem eos vero sequi beatae quo cumque, aut veritatis hic natus sint illum dolores voluptatibus, deleniti dolore blanditiis molestias fugiat quis quos! In iste eius illum natus fugit, at officiis minima unde voluptatibus perspiciatis voluptas distinctio omnis cumque tenetur facere nulla corporis officia vitae esse doloremque temporibus autem repudiandae? Neque sint tenetur quis fuga excepturi dolores aperiam voluptate, voluptatibus quia voluptatem quaerat earum error accusamus obcaecati, deleniti delectus laborum necessitatibus modi saepe nam iusto? Ut maxime, sit, et tempore facilis repudiandae quaerat voluptate minima recusandae optio veritatis excepturi cum porro voluptates ducimus praesentium distinctio qui quis dolore tempora. Nulla aut iusto numquam quia nemo reiciendis. Expedita alias numquam vero molestias facere nulla, optio a nisi tenetur possimus maiores ab vel corporis quam maxime repudiandae sit aut quaerat asperiores, blanditiis quidem? Eos minima porro facere amet suscipit ipsam qui quam ratione sapiente, tempora cum quas accusantium esse velit non perspiciatis et, odio, excepturi necessitatibus ipsum sequi itaque aspernatur. Repudiandae, at.</p>
        </section>
    )
}